/*------------------------------------------------------------------------------*
** <auto-generated
**      Editer :             liduoyou
**      Project starttime :  2016-03-04
**      Last modified :      2016-06-17
**      Running Version :    3.0.30319.296
**      Description :        This is an enter of all program>
** </auto-generated>
/*------------------------------------------------------------------------------*/
#include "MainWindow.h"
#include <QApplication>
#include <QTextCodec>
#include <QFontDatabase>
#include <QSplashScreen>
#include <QPixmap>
#include <QTranslator>
#include <QLocale>
#include <QDebug>
#include <QLibraryInfo>
#include <QDateTime>
#include "./Component/CardWidget.h"
#include "./DataHeaderDefine.h"
int main(int argc, char *argv[])
{
    QApplication app(argc, argv);

//    QString translatorFileName = QLatin1String("qt_");
//    translatorFileName += QLocale::system().name();
//    qDebug()<<"translatorFileName = "<<translatorFileName;
//    QTranslator *translator = new QTranslator(&app);
//    if (translator->load(translatorFileName, QLibraryInfo::location(QLibraryInfo::TranslationsPath)))
//        app.installTranslator(translator);
#ifdef TRANSLATOR
    QTranslator translator;
    translator.load(":/Main/international.qm");
    app.installTranslator(&translator);
#endif

#if QT_VERSION < QT_VERSION_CHECK(5,0,0)
    #if defined(_MSC_VER) && (_MSC_VER < 1600)
        QTextCodec::setCodecForTr(QTextCodec::codecForName("UTF-8"));
    #else
        QTextCodec::setCodecForTr(QTextCodec::codecForName("UTF-8"));
//        QTextCodec::setCodecForLocale(QTextCodec::codecForName("GB2312"));
    #endif
#endif
    //设置字体
#ifdef ARMCOMPILE
        //将字体文件名传给addApplicationFont,得到字体的Id
        int fontId = QFontDatabase::addApplicationFont("/lib/WenQuanYiMicroHeiMono.ttf");
        //将字体Id传给applicationFontFamilies,得到一个QStringList,其中的第一个元素为新添加字体的family
        QString msyh = QFontDatabase::applicationFontFamilies (fontId).at(0);
        QFont font(msyh,12);
        //将此字体设为QApplication的默认字体
        QApplication::setFont(font);
#else
        QFont font("wenquanyi",12);
        app.setFont(font);
#endif

    MainWindow mainWindow;

#if 0
    //交替加载并显示启动画面
    QSplashScreen screen(QPixmap(":/Main/Title.png").scaled(500,350,Qt::IgnoreAspectRatio));
    screen.setDisabled(true); //禁用用户的输入事件响应
    screen.setMouseTracking(true);
    screen.show();
    screen.showMessage(QObject::tr("系统加载中......30%"),Qt::AlignRight|Qt::AlignBottom,QColor("#0f9d58"));

    QDateTime n=QDateTime::currentDateTime();
    QDateTime now;
    do{
        now=QDateTime::currentDateTime();
        app.processEvents();
    }while (n.secsTo(now)<=1);//1为需要延时的秒数

    screen.showMessage(QObject::tr("系统加载中......60%"),Qt::AlignRight|Qt::AlignBottom,QColor("#0f9d58"));
    n=QDateTime::currentDateTime();
    do{
        now=QDateTime::currentDateTime();
        app.processEvents();
    }while (n.secsTo(now)<=1);

    screen.showMessage(QObject::tr("系统加载中......90%"),Qt::AlignRight|Qt::AlignBottom,QColor("#0f9d58"));
    n=QDateTime::currentDateTime();
    do{
        now=QDateTime::currentDateTime();
        app.processEvents();
    }while (n.secsTo(now)<=1);
#endif

    mainWindow.show();
#if 0
    screen.finish(&mainWindow);
#endif
    
    return app.exec();
}
